from django.urls import path
from .views import (
    LoginView,
    UserListCreateView,
    UserDetailView,
    CheckUserView,
    LoanListCreateView,
    LoanDetailView,
    LoanProductListCreateView,
    RepaymentListCreateView,
    AuditLogListView,
    AdminListCreateView,
    AdminDetailView,
    AdminDeleteView,
    RegisterAdminView,
    VerifyEmailView,
    RequestPasswordResetView,
    ConfirmPasswordResetView,
    UserProfileListCreateView,
    SystemSettingsView,
    LoanDocumentCreateView,
    NotificationListView,
    NotificationUpdateView,
    LoanAnalyticsView,
    MpesaRepaymentView,
    BulkSMSView,
    SMSLogListView,
    AdminInviteView,
)

urlpatterns = [
    path("sms-logs/", SMSLogListView.as_view(), name="sms-logs"),
    path("payments/mpesa/", MpesaRepaymentView.as_view(), name="mpesa-payment"),
    path("loans/bulk-sms-defaulters/", BulkSMSView.as_view(), name="bulk-sms"),
    path("notifications/", NotificationListView.as_view(), name="notifications"),
    path(
        "notifications/<int:pk>/",
        NotificationUpdateView.as_view(),
        name="notification-detail",
    ),
    path("loans/analytics/", LoanAnalyticsView.as_view(), name="loan-analytics"),
    path("auth/login/", LoginView.as_view(), name="login"),
    path("auth/register/", RegisterAdminView.as_view(), name="register"),
    path("auth/verify-email/", VerifyEmailView.as_view(), name="verify-email"),
    path(
        "auth/password-reset-request/",
        RequestPasswordResetView.as_view(),
        name="password-reset-request",
    ),
    path(
        "auth/password-reset-confirm/",
        ConfirmPasswordResetView.as_view(),
        name="password-reset-confirm",
    ),
    path("settings/", SystemSettingsView.as_view(), name="system-settings"),
    path("admins/", AdminListCreateView.as_view(), name="admins"),
    path("admins/<str:pk>/", AdminDetailView.as_view(), name="admin-detail"),
    path(
        "admins/<str:admin_id>/delete/", AdminDeleteView.as_view(), name="delete-admin"
    ),
    path("admins/invite/", AdminInviteView.as_view(), name="invite-admin"),
    path("users/", UserListCreateView.as_view(), name="users"),
    path("users/check/", CheckUserView.as_view(), name="check-user"),
    path("users/<str:pk>/", UserDetailView.as_view(), name="user-detail"),
    path("user-profiles/", UserProfileListCreateView.as_view(), name="user-profiles"),
    path("loans/", LoanListCreateView.as_view(), name="loans"),
    path("loans/<str:pk>/", LoanDetailView.as_view(), name="loan-detail"),
    path("loan-products/", LoanProductListCreateView.as_view(), name="loan-products"),
    path("repayments/", RepaymentListCreateView.as_view(), name="repayments"),
    path("loan-documents/", LoanDocumentCreateView.as_view(), name="loan-documents"),
    path("audit-logs/", AuditLogListView.as_view(), name="audit-logs"),
]
