# Generated by Django 6.0.2 on 2026-02-11 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_admins_password_reset_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_name', models.TextField(blank=True, null=True)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('status', models.CharField(default='SENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='apps.admins')),
            ],
            options={
                'db_table': 'sms_logs',
                'managed': True,
            },
        ),
    ]
