# Generated by Django 6.0.2 on 2026-02-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_admininvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='national_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='ids/'),
        ),
        migrations.AddField(
            model_name='userprofiles',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
