# Generated by Django 6.0.2 on 2026-02-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_userprofiles_national_id_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='status',
            field=models.TextField(db_index=True, default='UNVERIFIED'),
        ),
        migrations.AlterField(
            model_name='userprofiles',
            name='national_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
    ]
