# Generated by Django 6.0.2 on 2026-02-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0014_alter_loans_created_at_alter_loans_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproducts',
            name='duration_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='duration_weeks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loanproducts',
            name='duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
