# Generated by Django 6.0.2 on 2026-02-12 08:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_loanproducts_duration_weeks_loans_duration_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='log_type',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
        migrations.CreateModel(
            name='DeactivationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivation_requests', to='apps.admins')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_requests', to='apps.admins')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_deactivations', to='apps.admins')),
            ],
            options={
                'db_table': 'deactivation_requests',
                'managed': True,
            },
        ),
    ]
