# Generated by Django 6.0.2 on 2026-02-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_auditlogs_log_type_deactivationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
