# Generated by Django 6.0.2 on 2026-02-12 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_admins_is_super_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='region',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='userprofiles',
            old_name='county',
            new_name='branch',
        ),
        migrations.RemoveField(
            model_name='userprofiles',
            name='region',
        ),
    ]
