# Generated by Django 6.0.2 on 2026-02-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_rename_region_admins_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininvitation',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
