# Generated by Django 6.0.2 on 2026-02-13 07:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_admininvitation_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCapital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_capital',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_type', models.CharField(choices=[('DISBURSEMENT', 'Disbursement'), ('REPAYMENT', 'Repayment'), ('CAPITAL_INJECTION', 'Capital Injection'), ('FEES', 'Fees')], max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.loans')),
                ('capital_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.systemcapital')),
            ],
            options={
                'db_table': 'ledger_entries',
                'managed': True,
            },
        ),
    ]
