# Generated by Django 6.0.2 on 2026-02-13 07:04

from django.db import migrations


def seed_capital(apps, schema_editor):
    SystemCapital = apps.get_model("apps", "SystemCapital")
    SystemCapital.objects.get_or_create(
        name="Simulation Capital", defaults={"balance": 200000.00}
    )


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0020_systemcapital_ledgerentry"),
    ]

    operations = [
        migrations.RunPython(seed_capital),
    ]
