# Generated by Django 6.0.2 on 2026-02-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_alter_admins_phone_guarantors'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogs',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
