# Generated by Django 6.0.2 on 2026-02-13 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0023_auditlogs_ip_address_users_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='is_two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admins',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
