# Generated by Django 6.0.2 on 2026-02-13 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0024_admins_is_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admins',
            name='lockout_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_loans', to='apps.admins'),
        ),
        migrations.AddField(
            model_name='loans',
            name='status_change_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
