# Generated by Django 6.0.2 on 2026-02-14 08:52

from django.db import migrations


def update_loan_products(apps, schema_editor):
    LoanProducts = apps.get_model("apps", "LoanProducts")
    products_data = [
        {"name": "INUKA", "min": 3000, "max": 5000, "rate": 25.0, "weeks": 4},
        {"name": "JIJENGE", "min": 6000, "max": 10000, "rate": 31.25, "weeks": 5},
        {"name": "FADHILI", "min": 11000, "max": 50000, "rate": 36.35, "weeks": 6},
    ]

    for p in products_data:
        # Update existing records matching the name (case insensitive)
        updated_count = LoanProducts.objects.filter(name__iexact=p["name"]).update(
            min_amount=p["min"],
            max_amount=p["max"],
            interest_rate=p["rate"],
            duration_weeks=p["weeks"],
        )

        # If no records were updated, create a new one
        if updated_count == 0:
            LoanProducts.objects.create(
                name=p["name"].upper(),
                min_amount=p["min"],
                max_amount=p["max"],
                interest_rate=p["rate"],
                duration_weeks=p["weeks"],
            )


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0027_loans_disbursed_at_emaillog"),
    ]

    operations = [
        migrations.RunPython(update_loan_products),
    ]
