# Generated by Django 6.0.2 on 2026-02-14 09:05

from django.db import migrations


def remove_old_products(apps, schema_editor):
    LoanProducts = apps.get_model("apps", "LoanProducts")
    # Keep only the three specific products requested
    allowed_names = ["INUKA", "JIJENGE", "FADHILI"]

    # Delete any product whose name (case-insensitive) is not in the allowed list
    # We use Q objects for case-insensitive exclusion if needed, but iexact in a loop is safer
    all_products = LoanProducts.objects.all()
    for product in all_products:
        if product.name.upper() not in allowed_names:
            print(f"Deleting old product: {product.name}")
            product.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0028_update_loan_product_ranges"),
    ]

    operations = [
        migrations.RunPython(remove_old_products),
    ]
