# Generated by Django 6.0.2 on 2026-02-14 09:37

from django.db import migrations


def merge_to_canonical(apps, schema_editor):
    LoanProducts = apps.get_model("apps", "LoanProducts")
    Loans = apps.get_model("apps", "Loans")

    products_data = [
        {"name": "INUKA", "min": 3000, "max": 5000, "rate": 25.0, "weeks": 4},
        {"name": "JIJENGE", "min": 6000, "max": 10000, "rate": 31.25, "weeks": 5},
        {"name": "FADHILI", "min": 11000, "max": 50000, "rate": 36.35, "weeks": 6},
    ]

    canonical_map = {}
    for p in products_data:
        obj, created = LoanProducts.objects.get_or_create(
            name=p["name"],
            defaults={
                "min_amount": p["min"],
                "max_amount": p["max"],
                "interest_rate": p["rate"],
                "duration_weeks": p["weeks"],
            },
        )
        # Ensure range is correct even if it existed
        obj.min_amount = p["min"]
        obj.max_amount = p["max"]
        obj.interest_rate = p["rate"]
        obj.duration_weeks = p["weeks"]
        obj.save()
        canonical_map[p["name"]] = obj

    # Re-point existing loans to canonical products
    for loan in Loans.objects.all():
        p_name = loan.loan_product.name.upper()
        if "INUKA" in p_name and loan.loan_product != canonical_map["INUKA"]:
            loan.loan_product = canonical_map["INUKA"]
            loan.save()
        elif "JIJENGE" in p_name and loan.loan_product != canonical_map["JIJENGE"]:
            loan.loan_product = canonical_map["JIJENGE"]
            loan.save()
        elif "FADHILI" in p_name and loan.loan_product != canonical_map["FADHILI"]:
            loan.loan_product = canonical_map["FADHILI"]
            loan.save()

    # Safe delete others
    for p in LoanProducts.objects.all():
        if p.name not in ["INUKA", "JIJENGE", "FADHILI"]:
            try:
                p.delete()
            except:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0029_remove_old_loan_products"),
    ]

    operations = [
        migrations.RunPython(merge_to_canonical),
    ]
