# Generated by Django 6.0.2 on 2026-02-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0030_canonical_product_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='field_officer_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='manager_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
