# Generated by Django 6.0.2 on 2026-03-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_loans_field_officer_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
