# Generated by Django 6.0.2 on 2026-03-17 21:34

from django.db import migrations


def migrate_branches(apps, schema_editor):
    Admins = apps.get_model('apps', 'Admins')
    Branch = apps.get_model('apps', 'Branch')
    UserProfiles = apps.get_model('apps', 'UserProfiles')
    AdminInvitation = apps.get_model('apps', 'AdminInvitation')
    
    # Collect all unique branch names from existing records
    branch_names = set()
    branch_names.update(Admins.objects.exclude(branch__isnull=True).values_list('branch', flat=True))
    branch_names.update(UserProfiles.objects.exclude(branch__isnull=True).values_list('branch', flat=True))
    branch_names.update(AdminInvitation.objects.exclude(branch__isnull=True).values_list('branch', flat=True))
    
    # Create Branch objects
    branch_map = {}
    for name in branch_names:
        if name and name.strip():
            branch, created = Branch.objects.get_or_create(name=name.strip())
            branch_map[name.strip()] = branch
            
    # Link Admins
    for admin in Admins.objects.all():
        if admin.branch and admin.branch.strip() in branch_map:
            admin.branch_fk = branch_map[admin.branch.strip()]
            admin.save()
            
    # Link UserProfiles
    for profile in UserProfiles.objects.all():
        if profile.branch and profile.branch.strip() in branch_map:
            profile.branch_fk = branch_map[profile.branch.strip()]
            profile.save()
            
    # Link AdminInvitations
    for invite in AdminInvitation.objects.all():
        if invite.branch and invite.branch.strip() in branch_map:
            invite.branch_fk = branch_map[invite.branch.strip()]
            invite.save()

class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0033_branch_admininvitation_branch_fk_admins_branch_fk_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_branches),
    ]
