# Generated by Django 6.0.2 on 2026-03-18 06:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_migrate_branch_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_data', models.JSONField()),
                ('incomplete_reason', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_drafts', to='apps.admins')),
            ],
            options={
                'db_table': 'customer_drafts',
            },
        ),
    ]
