# Generated by Django 6.0.2 on 2026-03-18 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0035_customerdraft'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecureSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('encrypted_value', models.TextField()),
                ('setting_group', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.admins')),
            ],
            options={
                'db_table': 'secure_settings',
            },
        ),
    ]
