# Generated by Django 6.0.2 on 2026-03-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_securesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='admininvitation',
            name='invited_by_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to='apps.admins'),
        ),
        migrations.AddField(
            model_name='admins',
            name='god_mode_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admins',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_accounts', to='apps.admins'),
        ),
        migrations.AddField(
            model_name='admins',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admins',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admins',
            name='suspended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_accounts', to='apps.admins'),
        ),
        migrations.AddField(
            model_name='admins',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlogs',
            name='is_owner_log',
            field=models.BooleanField(default=False),
        ),
    ]
