# Generated by Django 6.0.2 on 2026-03-18 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0037_admininvitation_invited_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='is_primary_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admins',
            name='ownership_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admins',
            name='ownership_granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners_created', to='apps.admins'),
        ),
        migrations.AddField(
            model_name='admins',
            name='ownership_relinquished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
