# Generated by Django 6.0.2 on 2026-03-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0040_paybilltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='error_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
