# Generated by Django 6.0.2 on 2026-03-24 07:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0045_emaillog_email_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('CAPITAL_LOW', 'Capital Low Warning'), ('CAPITAL_CRITICAL', 'Capital Critically Low'), ('LARGE_DISBURSEMENT', 'Large Disbursement Alert'), ('VERIFICATION_BACKLOG', 'Verification Queue Backlog'), ('LOANS_STUCK', 'Loans Stuck In Pipeline'), ('OVERDUE_SPIKE', 'Overdue Loans Spike'), ('UNMATCHED_REPAYMENTS', 'Unmatched Repayments Sitting'), ('DISBURSEMENT_QUEUE', 'Disbursement Queue Alert'), ('STAFF_JOINED', 'New Staff Joined'), ('DEACTIVATION_REQUEST', 'Deactivation Request Submitted'), ('LOAN_REJECTED', 'Loan Rejected'), ('CUSTOMER_OVERDUE', 'Customer Gone Overdue'), ('SECURITY_THREAT', 'Security Threat Detected'), ('OFFICER_INACTIVE', 'Field Officer Inactive'), ('GOD_MODE_ACT', 'God Mode Act Session Started'), ('OWNERSHIP_CHANGE', 'Ownership Change'), ('STAFF_SUSPENDED', 'Staff Suspended')], max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('related_table', models.CharField(blank=True, max_length=100, null=True)),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_notifications', to='apps.admins')),
            ],
            options={
                'db_table': 'staff_notifications',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
