# Generated by Django 6.0.2 on 2026-03-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0046_staffnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='mpesa_disbursement_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='mpesa_originator_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
